Repository scalar-labs/scalar-terraform-examples, pull requests merged in 2021-04, with the labels that each got.

#20 Remove reference to cassandra remote state from scalardl module
  aws/README.md
  aws/cassandra/output.tf
  aws/scalardl/locals.tf
  aws/scalardl/main.tf
  aws/scalardl/remote.tf
  aws/scalardl/remote.tf.s3
  azure/README.md
  azure/cassandra/output.tf
  azure/scalardl/locals.tf
  azure/scalardl/main.tf
  azure/scalardl/remote.tf
  azure/scalardl/remote.tf.azurerm
Labels: improvement

#17 Update examples to use environment variables for scalar-ledger and scalar-auditor container
  .gitignore
  aws/scalardl/example.scalardl_container.env
  aws/scalardl/example.tfvars
  azure/scalardl/example.scalardl_container.env
  azure/scalardl/example.tfvars
  azure/scalardl/locals.tf
  azure/scalardl/main.tf
  azure/scalardl/remote.tf
  azure/scalardl/remote.tf.azurerm
Labels: enhancement

#21 Release v1.5.0
  aws/ca/main.tf
  aws/cassandra/main.tf
  aws/kubernetes/main.tf
  aws/monitor/main.tf
  aws/network/main.tf
  aws/pulsar/main.tf
  aws/scalardl/main.tf
  azure/ca/main.tf
  azure/cassandra/main.tf
  azure/cosmosdb/main.tf
  azure/kubernetes/main.tf
  azure/monitor/main.tf
  azure/network/main.tf
  azure/scalardl/main.tf
Labels: enhancement

#22 Release v1.4.0
  aws/ca/main.tf
  aws/cassandra/main.tf
  aws/monitor/main.tf
  aws/network/main.tf
  aws/pulsar/main.tf
  aws/scalardl/main.tf
  azure/ca/main.tf
  azure/cassandra/main.tf
  azure/kubernetes/main.tf
  azure/monitor/main.tf
  azure/network/main.tf
  azure/scalardl/main.tf
Labels: enhancement

#23 Update readme
  aws/README.md
  azure/README.md
Labels: documentation

#24 Release v1.3.3
  aws/ca/main.tf
  aws/cassandra/main.tf
  aws/monitor/main.tf
  aws/network/main.tf
  aws/scalardl/main.tf
  azure/ca/main.tf
  azure/cassandra/main.tf
  azure/monitor/main.tf
  azure/network/main.tf
  azure/scalardl/main.tf
Labels: enhancement

#26 Fix broken links in README
  aws/README.md
  azure/README.md
Labels: bugfix

#25 Release v1.2.3
  aws/ca/main.tf
  aws/cassandra/main.tf
  aws/monitor/main.tf
  aws/network/main.tf
  aws/scalardl/main.tf
  azure/ca/main.tf
  azure/cassandra/main.tf
  azure/monitor/main.tf
  azure/network/main.tf
  azure/scalardl/main.tf
Labels: enhancement

#27 Update documentation about the environment file
  aws/README.md
  azure/README.md
Labels: documentation
