Repository scalar-labs/scalar-terraform-examples, pull requests merged in 2021-02, with the labels that each got.

#7 Disable autoscaling by defaulte for azure k8s
  azure/kubernetes/example.tfvars
Labels: improvement

#9 Specify cluster accessibility simply for eks
  aws/kubernetes/example.tfvars
Labels: improvement

#8 Enable to configure cluster accessibility for aks
  azure/kubernetes/example.tfvars
Labels: improvement

#10 Add autoscaling flag for eks
  aws/kubernetes/example.tfvars
Labels: enhancement

#12 Fix the hostnames of Cassy and Reaper
  aws/README.md
Labels: documentation

#11 Output inventory ini
  aws/ca/output.tf
  aws/cassandra/output.tf
  aws/monitor/output.tf
  aws/network/output.tf
  aws/scalardl/output.tf
  azure/ca/output.tf
  azure/cassandra/output.tf
  azure/monitor/output.tf
  azure/network/output.tf
  azure/scalardl/output.tf
Labels: enhancement
